AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  testlambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: testlambda.lambda_handler
      Runtime: python3.8
      Policies: AmazonDynamoDBFullAccess
